@echo off
echo Open Watcom Build Environment
SET PATH=%USERPROFILE%\EUPHORIA\WATCOM\BINW;%PATH%
SET PATH=%USERPROFILE%\EUPHORIA\WATCOM\BINNT;%PATH%
SET INCLUDE=%USERPROFILE%\EUPHORIA\WATCOM\H\NT;%INCLUDE%
SET INCLUDE=%USERPROFILE%\EUPHORIA\WATCOM\H\NT;%INCLUDE%
SET INCLUDE=%INCLUDE%;%USERPROFILE%\EUPHORIA\WATCOM\H\NT\DIRECTX
SET INCLUDE=%INCLUDE%;%USERPROFILE%\EUPHORIA\WATCOM\H\NT\DDK
SET INCLUDE=%USERPROFILE%\EUPHORIA\WATCOM\H;%INCLUDE%
SET WATCOM=%USERPROFILE%\EUPHORIA\WATCOM
SET EDPATH=%USERPROFILE%\EUPHORIA\WATCOM\EDDAT
SET WHTMLHELP=%USERPROFILE%\EUPHORIA\WATCOM\BINNT\HELP
SET WIPFC=%USERPROFILE%\EUPHORIA\WATCOM\WIPFC
